# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-firebase-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-firebase-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-firebase-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-firebase-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SECRET_KEY=your-secret-key,FIREBASE_CREDENTIALS=/secrets/firebase-credentials.json'
      - '--set-secrets'
      - '/secrets/firebase-credentials.json=firebase-credentials:latest'

images:
  - 'gcr.io/$PROJECT_ID/flask-firebase-app'
